import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, it } from 'node:test';
import { findUnsupportedKeywords, type JsonSchema } from '../../src/core/schema';
import { tools } from '../../src/tools';

/**
 * Keeps package.json and the code in sync: a tool registered in code but missing from the
 * manifest (or vice versa) fails here instead of at runtime in a user's VS Code.
 */

const root = resolve(__dirname, '../../..');
const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8')) as {
  main: string;
  engines: { vscode: string };
  activationEvents?: string[];
  devDependencies: Record<string, string>;
  contributes: {
    languageModelTools: {
      name: string; displayName?: string; toolReferenceName?: string; canBeReferencedInPrompt?: boolean;
      userDescription?: string; modelDescription?: string; tags?: string[]; inputSchema?: JsonSchema;
    }[];
  };
};
const declared = pkg.contributes.languageModelTools;

describe('manifest', () => {
  it('declares exactly the tools registered in code', () => {
    assert.deepEqual(declared.map((t) => t.name).sort(), tools.map((t) => t.name).sort());
  });

  it('gives every tool the fields VS Code requires and users need', () => {
    for (const t of declared) {
      assert.ok(t.displayName && t.modelDescription && t.userDescription, t.name);
      assert.match(t.name, /^(?!copilot_|vscode_)[\w-]+$/);
      if (t.canBeReferencedInPrompt) {
        assert.match(t.toolReferenceName ?? '', /^[\w-]+$/, `${t.name} needs toolReferenceName`);
      }
      for (const tag of t.tags ?? []) {
        assert.doesNotMatch(tag, /^(copilot_|vscode_)/);
      }
    }
  });

  it('uses only schema keywords the runtime validator enforces', () => {
    for (const t of declared) {
      assert.equal(t.inputSchema?.type, 'object', `${t.name} inputSchema must be an object`);
      assert.deepEqual(findUnsupportedKeywords(t.inputSchema), [], t.name);
    }
  });

  it('declares form fields that exist in the input schema', () => {
    for (const tool of tools) {
      if (typeof tool.review !== 'function' && tool.review.kind === 'form') {
        const properties = Object.keys(declared.find((t) => t.name === tool.name)?.inputSchema?.properties ?? {});
        for (const field of tool.review.form.fields) {
          assert.ok(properties.includes(field.key), `${tool.name}: form field '${field.key}' is not in inputSchema`);
        }
      }
    }
  });

  it('marks every mutate tool so reviewers can see it', () => {
    for (const tool of tools.filter((t) => t.category === 'mutate')) {
      assert.ok(declared.find((t) => t.name === tool.name)?.tags?.includes('mutate'), tool.name);
    }
  });

  it('compiles against the minimum VS Code version it declares', () => {
    const engine = pkg.engines.vscode.replace(/^\^/, '');
    assert.equal(pkg.devDependencies['@types/vscode'], engine, '@types/vscode must equal the engines.vscode minimum so newer APIs fail to compile');
  });

  it('points main at the compiled entry point and relies on implicit activation', () => {
    assert.equal(pkg.main, './out/src/extension.js');
    assert.ok(existsSync(resolve(root, pkg.main)), 'run npm run compile first');
    assert.deepEqual(pkg.activationEvents ?? [], [], 'onLanguageModelTool:<name> events are generated by VS Code from contributes.languageModelTools');
  });
});
